import { Button } from '@chakra-ui/button';
import { Heading, Text } from '@chakra-ui/layout';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heading variant="title" size="lg">
        My little test
      </Heading>

      <Text variant="subTitle">Subtitle</Text>
      <Text variant="info">Info</Text>
      <Text variant="highlight">HighLight</Text>

      <Button variant="primary">Sair do modo Preview</Button>
    </div>
  );
};

export default Home;
